---
abstract: 'LEGO City Undercover theme'
author:
  - 'Chris Williams'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::MetaSyntactic: 0
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-MetaSyntactic-legocityundercover
requires:
  Acme::MetaSyntactic::List: 1.001
  perl: v5.6.0
resources:
  homepage: https://github.com/bingos/acme-metasyntactic-legocityundercover
  repository: https://github.com/bingos/acme-metasyntactic-legocityundercover.git
version: 0.02
